INSERT INTO vehicles (id, name, license_plate, brand, type, seat_count, manufacture_year, description, rental_price, vehicle_condition, owner_type)
VALUES
(1, 'Toyota Innova', '51H-12345', 'Toyota', 'MPV', 7, 2020, 'Toyota Innova là dòng xe MPV rất phổ biến tại Việt Nam, được nhiều gia đình và doanh nghiệp tin dùng. Xe có thiết kế rộng rãi với 7 chỗ ngồi thoải mái, khoang hành lý lớn phù hợp cho những chuyến đi xa. Động cơ của Innova được đánh giá là bền bỉ, dễ bảo dưỡng. Ngoài ra, xe còn trang bị nhiều tính năng an toàn cơ bản, phù hợp với nhu cầu sử dụng hằng ngày. Đây là sự lựa chọn đáng tin cậy cho khách hàng muốn thuê xe gia đình.', 800000.0, 'GOOD', 'STORE'),
(2, 'Honda CR-V', '51G-67890', 'Honda', 'SUV', 5, 2021, 'Honda CR-V mang lại trải nghiệm lái mượt mà và hiện đại. Xe có khoang nội thất tiện nghi, tích hợp nhiều công nghệ như hỗ trợ giữ làn, cảnh báo va chạm và phanh tự động. Không gian bên trong rộng rãi, ghế ngồi thoải mái cho cả 5 hành khách. CR-V có kiểu dáng thể thao, động cơ tiết kiệm nhiên liệu. Phù hợp với nhóm khách gia đình hoặc khách công tác dài ngày.', 1000000.0, 'EXCELLENT', 'STORE'),
(3, 'Hyundai Accent', '51F-23456', 'Hyundai', 'Sedan', 5, 2019, 'Hyundai Accent là chiếc sedan nhỏ gọn lý tưởng cho các tuyến đường nội thành. Với thiết kế hiện đại và khả năng vận hành ổn định, Accent đáp ứng tốt nhu cầu đi lại cá nhân hoặc theo nhóm nhỏ. Xe có khả năng tiết kiệm nhiên liệu tốt, đồng thời nội thất được thiết kế tối ưu hóa không gian. Đây là mẫu xe phù hợp cho người mới lái hoặc khách cần di chuyển linh hoạt.', 600000.0, 'GOOD', 'STORE'),
(4, 'Kia Seltos', '51E-78901', 'Kia', 'SUV', 5, 2022, 'Kia Seltos sở hữu ngoại hình bắt mắt với thiết kế trẻ trung, thể thao. Nội thất bên trong hiện đại, được trang bị màn hình giải trí trung tâm và hệ thống âm thanh sống động. Seltos phù hợp cho các chuyến đi du lịch hoặc công tác. Khả năng vận hành ổn định trên nhiều loại địa hình là một điểm mạnh lớn. Xe còn tích hợp nhiều tính năng an toàn như cảm biến, camera lùi.', 900000.0, 'EXCELLENT', 'STORE'),
(5, 'Ford Racustomersusersnger', '51D-34567', 'Ford', 'Pickup', 5, 2020, 'Ford Ranger là dòng bán tải mạnh mẽ, phù hợp cho những chuyến đi xa hoặc chuyên chở hàng hóa. Xe có động cơ Diesel bền bỉ, tiết kiệm nhiên liệu. Cabin rộng rãi, tiện nghi với các trang bị hiện đại như màn hình cảm ứng, điều hòa tự động. Ranger có khả năng vượt địa hình tốt, gầm cao giúp di chuyển dễ dàng ở vùng cao hay vùng ngập.', 1200000.0, 'GOOD', 'STORE'),
(6, 'Mazda CX-5', '51C-89012', 'Mazda', 'SUV', 5, 2021, 'Mazda CX-5 nổi bật với thiết kế KODO sang trọng, tinh tế. Nội thất bọc da cao cấp, vô-lăng tích hợp nút điều khiển và hệ thống giải trí hiện đại. Xe vận hành êm ái, cách âm tốt, phù hợp cho khách hàng yêu cầu cao về trải nghiệm lái. CX-5 là lựa chọn tuyệt vời cho gia đình hoặc người đi công tác cần sự thoải mái và an toàn.', 950000.0, 'EXCELLENT', 'STORE'),
(7, 'Toyota Vios', '51B-45678', 'Toyota', 'Sedan', 5, 2018, 'Toyota Vios là mẫu sedan được ưa chuộng nhiều năm liền nhờ độ bền cao và chi phí sử dụng thấp. Xe có thiết kế đơn giản nhưng hiệu quả, vận hành nhẹ nhàng trong đô thị. Nội thất tiện nghi cơ bản, phù hợp với nhu cầu di chuyển hàng ngày. Vios là lựa chọn hàng đầu cho người cần thuê xe giá rẻ và ổn định.', 550000.0, 'GOOD', 'STORE'),
(8, 'VinFast Lux A2.0', '51A-90123', 'VinFast', 'Sedan', 5, 2020, 'VinFast Lux A2.0 mang lại trải nghiệm lái cao cấp nhờ khung gầm được phát triển từ BMW. Xe có nội thất rộng rãi, hệ thống giải trí cảm ứng, điều hòa tự động 2 vùng. Động cơ mạnh mẽ giúp xe tăng tốc nhanh, cảm giác lái đầm chắc. Đây là mẫu xe sedan cao cấp phù hợp với khách hàng doanh nhân hoặc người muốn trải nghiệm thương hiệu Việt.', 850000.0, 'GOOD', 'STORE'),
(9, 'Mitsubishi Xpander', '51K-56789', 'Mitsubishi', 'MPV', 7, 2021, 'Mitsubishi Xpander được biết đến với khả năng chở 7 người thoải mái, thiết kế hiện đại và tiết kiệm nhiên liệu. Xe có khoang hành lý rộng, phù hợp cho gia đình hoặc nhóm du lịch. Nội thất bền bỉ, vận hành ổn định, giá thuê hợp lý. Đây là mẫu MPV phổ thông rất được ưa chuộng tại Việt Nam.', 750000.0, 'GOOD', 'STORE'),
(10, 'Suzuki Ertiga', '51M-01234', 'Suzuki', 'MPV', 7, 2020, 'Suzuki Ertiga là mẫu xe 7 chỗ với giá thành hợp lý, thích hợp cho khách hàng thuê đi tỉnh hoặc đi du lịch cuối tuần. Xe có động cơ tiết kiệm, nội thất bố trí hợp lý, điều hòa 2 vùng cho hàng ghế sau. Ertiga nhẹ nhàng, dễ lái, phù hợp với nhu cầu sử dụng đơn giản.', 700000.0, 'GOOD', 'STORE'),
(11, 'Hyundai Tucson', '52A-67890', 'Hyundai', 'SUV', 5, 2022, 'Hyundai Tucson mang dáng vẻ hiện đại, đậm chất châu Âu. Xe có không gian rộng rãi, trang bị hệ thống an toàn chủ động như cảnh báo điểm mù, hỗ trợ đỗ xe và cruise control thông minh. Động cơ mạnh mẽ, vận hành mượt mà. Tucson thích hợp cho những khách hàng yêu thích trải nghiệm cao cấp và an toàn.', 970000.0, 'EXCELLENT', 'STORE'),
(12, 'Kia Carnival', '52B-12345', 'Kia', 'MPV', 7, 2023, 'Kia Carnival là mẫu xe gia đình cao cấp với thiết kế đậm chất sang trọng. Khoang nội thất cực kỳ rộng rãi, đầy đủ tiện nghi như ghế chỉnh điện, màn hình giải trí cho hàng ghế sau và điều hòa đa vùng. Xe phù hợp cho các chuyến du lịch dài hoặc đưa đón khách VIP.', 1100000.0, 'EXCELLENT', 'STORE'),
(13, 'Toyota Fortuner', '52C-23456', 'Toyota', 'SUV', 7, 2021, 'Toyota Fortuner là mẫu SUV 7 chỗ mạnh mẽ, gầm cao, khả năng vận hành đa địa hình vượt trội. Nội thất tiện nghi, có nhiều tính năng hỗ trợ lái và an toàn. Xe thích hợp cho cả mục đích gia đình và công việc cần di chuyển đường dài hoặc khu vực đồi núi.', 1150000.0, 'GOOD', 'STORE'),
(14, 'Honda City', '52D-34567', 'Honda', 'Sedan', 5, 2019, 'Honda City là lựa chọn lý tưởng cho khách hàng trẻ năng động. Với thiết kế thể thao, động cơ tiết kiệm và khả năng xử lý linh hoạt, City đáp ứng tốt nhu cầu di chuyển trong đô thị. Nội thất đơn giản nhưng tiện nghi, dễ sử dụng.', 580000.0, 'GOOD', 'STORE'),
(15, 'Mazda 3', '52E-45678', 'Mazda', 'Sedan', 5, 2020, 'Mazda 3 mang đậm phong cách thiết kế KODO sắc sảo, nội thất hiện đại như một chiếc xe sang. Hệ thống cách âm tốt, cảm giác lái mượt mà và tiết kiệm nhiên liệu. Đây là mẫu xe rất được ưa chuộng trong phân khúc sedan hạng C.', 750000.0, 'GOOD', 'STORE');
